<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
      DB::table('genres')->insert([
          [
              'id' => 1 ,
              'name' => "Drama" ,
          ],
          [
              'id' => 2 ,
              'name' => "Kids" ,
          ],
          [
              'id' => 3 ,
              'name' => "Tv Shows" ,
          ],
      ]);

      DB::table('movies')->insert([
          [
              'id' => 1 ,
              'genre_id' => 1 ,
              'title' => "It's Okay to Not Be Okay" ,
              'photo' => "https://i.mydramalist.com/xw3xX_4f.jpg" ,
              'description' => "It's Okay to Not Be Okay adalah seri televisi Korea Selatan tahun 2020 yang dibintangi oleh Kim Soo-hyun, Seo Ye-ji, Oh Jung-se, dan Park Gyu-young. Drama ini menceritakan hubungan asmara tidak biasa antara dua orang yang akhirnya saling menyembuhkan luka emosional dan psikologis satu sama lain." ,
              'rating' => 4 ,
          ],
          [
              'id' => 2 ,
              'genre_id' => 1 ,
              'title' => "Crash Landing on You" ,
              'photo' => "https://asianwiki.com/images/f/f8/Crash_Landing_on_You-P1.jpg" ,
              'description' => "Crash Landing on You (Korea: 사랑 의 불시착; RR: Sarangui Bulsichak; MR: Sarangŭi pulshich'ak; lit. Love's Emergency Landing) adalah serial televisi Korea Selatan yang disutradarai oleh Lee Jeong-hyo dan menampilkan Hyun Bin, Son Ye-jin , Kim Jung-hyun, dan Seo Ji-hye. Ini tentang pewaris chaebol Korea Selatan yang, saat paralayang di Seoul, Korea Selatan, tiba-tiba tersapu badai dan mendarat di bagian Korea Utara dari DMZ." ,
              'rating' => 5 ,
          ],
          [
              'id' => 3 ,
              'genre_id' => 1 ,
              'title' => "Hospital Playlist" ,
              'photo' => "https://asianwiki.com/images/c/ca/Hospital_Playlist-P1.jpg" ,
              'description' => "Hospital Playlist adalah seri televisi Korea Selatan tahun 2020 yang ditulis oleh Lee Woo-jung dan disutradarai oleh Shin Won-ho. Ini juga merupakan drama kedua dari seri Wise Life setelah Prison Playbook. Drama ini dibintangi oleh Jo Jung-suk, Yoo Yeon-seok, Jung Kyung-ho, Kim Dae-myung, dan Jeon Mi-do." ,
              'rating' => 4 ,
          ],
          [
              'id' => 4 ,
              'genre_id' => 1 ,
              'title' => "The World of the Married" ,
              'photo' => "https://upload.wikimedia.org/wikipedia/en/thumb/7/76/The_World_of_the_Married.jpg/250px-The_World_of_the_Married.jpg" ,
              'description' => "The World of the Married (Bahasa Korea: 부부 의 세계; Hanja: 夫婦 의 世界; RR: Bubu-ui Segye; lit. Couple's World) adalah serial televisi Korea Selatan tahun 2020 yang dibintangi oleh Kim Hee-ae, Park Hae-joon, dan Han So-hee. Berdasarkan serial drama BBC One Doctor Foster yang ditulis oleh Mike Bartlett, ini menceritakan kisah pasangan menikah yang pengkhianatan satu sama lain mengarah ke angin puyuh balas dendam, kesedihan, pengampunan dan penyembuhan." ,
              'rating' => 5 ,
          ],
          [
              'id' => 5 ,
              'genre_id' => 1 ,
              'title' => "Dora and the Lost City of Gold" ,
              'photo' => "https://upload.wikimedia.org/wikipedia/en/thumb/2/29/Dora_and_the_Lost_City_of_Gold_poster.jpg/220px-Dora_and_the_Lost_City_of_Gold_poster.jpg" ,
              'description' => "Diangkat dari serial televisi yang sangat populer. Dora (Isabela Moner), seorang penjelajah muda, memimpin teman-temannya dalam petualangan untuk menyelamatkan orangtuanya dan memecahkan misteri di balik kota emas yang hilang." ,
              'rating' => 5 ,
          ],
          [
              'id' => 6 ,
              'genre_id' => 1 ,
              'title' => "How to Train Your Dragon: The Hidden World" ,
              'photo' => "https://cdn.cgv.id/uploads/movie/compressed/18042800.jpg" ,
              'description' => "How to Train Your Dragon: The Hidden World adalah film fantasi laga animasi komputer 3D Amerika Serikat tahun 2019 yang diproduksi oleh DreamWorks Animation dan didistribusikan oleh Universal Pictures. Film ini dibuat berdasarkan seri buku Inggris dengan nama yang sama oleh Cressida Cowell. Film ini adalah sekuel film animasi-komputer 2014 How to Train Your Dragon 2 dan yang ketiga dalam trilogi. Ditulis dan disutradarai oleh Dean DeBlois, film ini dibintangi oleh suara-suara Jay Baruchel, America Ferrera, Cate Blanchett, Craig Ferguson, dan F. Murray Abraham. Alur cerita film ini mengikuti Hiccup mencari utopia naga yang disebut The Hidden World sementara berdamai dengan ikat baru Toothless dengan Light Fury wanita." ,
              'rating' => 4 ,
          ],
          [
              'id' => 7 ,
              'genre_id' => 1 ,
              'title' => "Ralph Breaks the Internet: Wreck-It Ralph" ,
              'photo' => "https://cdn0-production-images-kly.akamaized.net/0P4b6F7NF3SzbmQZYPAhitGRGaQ=/375x500/smart/filters:quality(75):strip_icc():format(jpeg)/kly-media-production/medias/2386081/original/088343800_1539779798-Wreck_2.jpg" ,
              'description' => "Petualangan Baru Ralph dan Vanellope akan berlanjut dalam Ralph Breaks the Internet. 6 tahun pasca Wreck-It Ralph, Ralph dan Vanellope kini semakin jauh menjelajah ke dunia maya." ,
              'rating' => 4 ,
          ],
          [
              'id' => 8 ,
              'genre_id' => 1 ,
              'title' => "Toy Story 4" ,
              'photo' => "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRPJMUPYT0xhPoO1-fjg-SpE9PzGSuVIHJdDGrOLh1hr-HDXuMx" ,
              'description' => "Woody selalu merasa percaya diri akan posisinya di dunia, dan prioritasnya adalah menjaga anaknya, baik itu Andy atau Bonnie. Namun ketika Bonnie menambahkan sebuah mainan baru bernama Forky dalam kamar mainannya, sebuah pengembaraan bersama teman-teman lama dan baru akan membawa Woody untuk menyaksikan betapa besarnya dunia ini bagi sebuah mainan seperti dirinya." ,
              'rating' => 5 ,
          ],
          [
              'id' => 9 ,
              'genre_id' => 1 ,
              'title' => "Record of Youth" ,
              'photo' => "https://upload.wikimedia.org/wikipedia/en/thumb/a/ab/Record_of_Youth.jpg/250px-Record_of_Youth.jpg" ,
              'description' => "Sa Hye-Jun (Park Bo-Gum) is smart and handsome. He is a nice guy and a popular model, but what he really wants is to become an actor. He has auditioned for many acting roles, but hasn't found success yet. Unfortunately, Sa Hye-Jun doesn't have much presence as an actor. Meanwhile, An Jeong-Ha (Park So-Dam) works as a make-up artist." ,
              'rating' => 3 ,
          ],
          [
              'id' => 10 ,
              'genre_id' => 1 ,
              'title' => "Elite" ,
              'photo' => "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcToQhzCqCpR4ohtfMhyujHthb7Z7z_hwE5kzr3iS1d1WXNEZbDp" ,
              'description' => "Elite (Spanish: Élite; stylized as E L I T Ǝ) is a Spanish thriller teen drama streaming television series created for Netflix by Carlos Montero and Darío Madrona. The series is set in Las Encinas, a fictional elite secondary school and revolves around the relationships between three working-class teenage students enrolled at the school through a scholarship and their wealthy classmates. The series features an ensemble cast including María Pedraza, Itzan Escamilla, Miguel Bernardeau, Miguel Herrán, Jaime Lorente, Álvaro Rico, Arón Piper, Mina El Hammani, Ester Expósito, Omar Ayuso, and Danna Paola. Jorge López, Claudia Salas, Georgina Amorós, Sergio Momo, Leïti Sène, Carla Díaz, Manu Ríos, Martina Cariddi, and Pol Granch joined the cast in later seasons. Many of the cast previously featured in other Netflix works produced or distributed in Spain and Latin America." ,
              'rating' => 3 ,
          ],
          [
              'id' => 11 ,
              'genre_id' => 1 ,
              'title' => "Peaky Blinders" ,
              'photo' => "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTGyDDzYHvg_BMX5bESg8Mky8zb5F89Zwkkd2KoAg1gnJqbQxIY" ,
              'description' => "Peaky Blinders adalah serial televisi drama kriminal Inggris yang dibuat oleh Steven Knight. Berlatar di Birmingham, Inggris, serial ini mengikuti eksploitasi keluarga kriminal Shelby setelah langsung Perang Dunia Pertama." ,
              'rating' => 5 ,
          ],
          [
              'id' => 12 ,
              'genre_id' => 1 ,
              'title' => "The Umbrella Academy" ,
              'photo' => "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTGmLFCbr45HyfANTQHdeayH8zeVsozrKiScdROp5OuhstmENRe" ,
              'description' => "The Umbrella Academy adalah serial televisi web superhero Amerika Serikat yang berdasarkan pada seri buku komik dengan nama yang sama yang diterbitkan oleh Dark Horse Comics." ,
              'rating' => 5 ,
          ],
      ]);

      DB::table('episodes')->insert([
          [
            'id' => 1 ,
            'movie_id' => 1 ,
            'episode' => 1 ,
            'title' => " Magnet " ,
          ],
          [
            'id' => 2 ,
            'movie_id' => 1 ,
            'episode' => 2 ,
            'title' => " Days " ,
          ],
          [
            'id' => 3 ,
            'movie_id' => 1 ,
            'episode' => 3 ,
            'title' => " Mattresses " ,
          ],
          [
            'id' => 4 ,
            'movie_id' => 1 ,
            'episode' => 4 ,
            'title' => " Scratches " ,
          ],
          [
            'id' => 5 ,
            'movie_id' => 1 ,
            'episode' => 5 ,
            'title' => " Mouths " ,
          ],
          [
            'id' => 6 ,
            'movie_id' => 1 ,
            'episode' => 6 ,
            'title' => " Hums " ,
          ],
          [
            'id' => 7 ,
            'movie_id' => 1 ,
            'episode' => 7 ,
            'title' => " Labors " ,
          ],
          [
            'id' => 8 ,
            'movie_id' => 1 ,
            'episode' => 8 ,
            'title' => " Crimes " ,
          ],
          [
            'id' => 9 ,
            'movie_id' => 1 ,
            'episode' => 9 ,
            'title' => " Transmissions " ,
          ],
          [
            'id' => 10 ,
            'movie_id' => 2 ,
            'episode' => 1 ,
            'title' => " Latitudes " ,
          ],
          [
            'id' => 11 ,
            'movie_id' => 2 ,
            'episode' => 2 ,
            'title' => " Military " ,
          ],
          [
            'id' => 12 ,
            'movie_id' => 2 ,
            'episode' => 3 ,
            'title' => " Butts " ,
          ],
          [
            'id' => 13 ,
            'movie_id' => 2 ,
            'episode' => 4 ,
            'title' => " Cover " ,
          ],
          [
            'id' => 14 ,
            'movie_id' => 2 ,
            'episode' => 5 ,
            'title' => " Shipment " ,
          ],
          [
            'id' => 15 ,
            'movie_id' => 2 ,
            'episode' => 6 ,
            'title' => " Hoods " ,
          ],
          [
            'id' => 16 ,
            'movie_id' => 2 ,
            'episode' => 7 ,
            'title' => " Gases " ,
          ],
          [
            'id' => 17 ,
            'movie_id' => 2 ,
            'episode' => 8 ,
            'title' => " Waxes " ,
          ],
          [
            'id' => 18 ,
            'movie_id' => 2 ,
            'episode' => 9 ,
            'title' => " Sabotage " ,
          ],
          [
            'id' => 19 ,
            'movie_id' => 3 ,
            'episode' => 1 ,
            'title' => " Letterhead " ,
          ],
          [
            'id' => 20 ,
            'movie_id' => 3 ,
            'episode' => 2 ,
            'title' => " Pad " ,
          ],
          [
            'id' => 21 ,
            'movie_id' => 3 ,
            'episode' => 3 ,
            'title' => " Preparations " ,
          ],
          [
            'id' => 22 ,
            'movie_id' => 3 ,
            'episode' => 4 ,
            'title' => " Analyzers " ,
          ],
          [
            'id' => 23 ,
            'movie_id' => 3 ,
            'episode' => 5 ,
            'title' => " Mirror " ,
          ],
          [
            'id' => 24 ,
            'movie_id' => 3 ,
            'episode' => 6 ,
            'title' => " Yolk " ,
          ],
          [
            'id' => 25 ,
            'movie_id' => 3 ,
            'episode' => 7 ,
            'title' => " Tape " ,
          ],
          [
            'id' => 26 ,
            'movie_id' => 3 ,
            'episode' => 8 ,
            'title' => " Path " ,
          ],
          [
            'id' => 27 ,
            'movie_id' => 3 ,
            'episode' => 9 ,
            'title' => " Enlistment " ,
          ],
          [
            'id' => 28 ,
            'movie_id' => 4 ,
            'episode' => 1 ,
            'title' => " Fuel " ,
          ],
          [
            'id' => 29 ,
            'movie_id' => 4 ,
            'episode' => 2 ,
            'title' => " Extension " ,
          ],
          [
            'id' => 30 ,
            'movie_id' => 4 ,
            'episode' => 3 ,
            'title' => " Fits " ,
          ],
          [
            'id' => 31 ,
            'movie_id' => 4 ,
            'episode' => 4 ,
            'title' => " Torpedo " ,
          ],
          [
            'id' => 32 ,
            'movie_id' => 4 ,
            'episode' => 5 ,
            'title' => " Apron " ,
          ],
          [
            'id' => 33 ,
            'movie_id' => 4 ,
            'episode' => 6 ,
            'title' => " Quotas " ,
          ],
          [
            'id' => 34 ,
            'movie_id' => 4 ,
            'episode' => 7 ,
            'title' => " Glides " ,
          ],
          [
            'id' => 35 ,
            'movie_id' => 4 ,
            'episode' => 8 ,
            'title' => " Vehicles " ,
          ],
          [
            'id' => 36 ,
            'movie_id' => 4 ,
            'episode' => 9 ,
            'title' => " Changes " ,
          ],
          [
            'id' => 37 ,
            'movie_id' => 5 ,
            'episode' => 1 ,
            'title' => " Banks " ,
          ],
          [
            'id' => 38 ,
            'movie_id' => 5 ,
            'episode' => 2 ,
            'title' => " Friday " ,
          ],
          [
            'id' => 39 ,
            'movie_id' => 5 ,
            'episode' => 3 ,
            'title' => " Measurements " ,
          ],
          [
            'id' => 40 ,
            'movie_id' => 5 ,
            'episode' => 4 ,
            'title' => " Commission " ,
          ],
          [
            'id' => 41 ,
            'movie_id' => 5 ,
            'episode' => 5 ,
            'title' => " Poles " ,
          ],
          [
            'id' => 42 ,
            'movie_id' => 5 ,
            'episode' => 6 ,
            'title' => " Sponsor " ,
          ],
          [
            'id' => 43 ,
            'movie_id' => 5 ,
            'episode' => 7 ,
            'title' => " Cables " ,
          ],
          [
            'id' => 44 ,
            'movie_id' => 5 ,
            'episode' => 8 ,
            'title' => " Seamanship " ,
          ],
          [
            'id' => 45 ,
            'movie_id' => 5 ,
            'episode' => 9 ,
            'title' => " Subfunction " ,
          ],
          [
            'id' => 46 ,
            'movie_id' => 6 ,
            'episode' => 1 ,
            'title' => " Trust " ,
          ],
          [
            'id' => 47 ,
            'movie_id' => 6 ,
            'episode' => 2 ,
            'title' => " Whirls " ,
          ],
          [
            'id' => 48 ,
            'movie_id' => 6 ,
            'episode' => 3 ,
            'title' => " Bite " ,
          ],
          [
            'id' => 49 ,
            'movie_id' => 6 ,
            'episode' => 4 ,
            'title' => " Desire " ,
          ],
          [
            'id' => 50 ,
            'movie_id' => 6 ,
            'episode' => 5 ,
            'title' => " Chip " ,
          ],
          [
            'id' => 51 ,
            'movie_id' => 6 ,
            'episode' => 6 ,
            'title' => " Implement " ,
          ],
          [
            'id' => 52 ,
            'movie_id' => 6 ,
            'episode' => 7 ,
            'title' => " Minuses " ,
          ],
          [
            'id' => 53 ,
            'movie_id' => 6 ,
            'episode' => 8 ,
            'title' => " Restriction " ,
          ],
          [
            'id' => 54 ,
            'movie_id' => 6 ,
            'episode' => 9 ,
            'title' => " Prefixes " ,
          ],
          [
            'id' => 55 ,
            'movie_id' => 7 ,
            'episode' => 1 ,
            'title' => " Member " ,
          ],
          [
            'id' => 56 ,
            'movie_id' => 7 ,
            'episode' => 2 ,
            'title' => " Spoke " ,
          ],
          [
            'id' => 57 ,
            'movie_id' => 7 ,
            'episode' => 3 ,
            'title' => " Wrap " ,
          ],
          [
            'id' => 58 ,
            'movie_id' => 7 ,
            'episode' => 4 ,
            'title' => " Pages " ,
          ],
          [
            'id' => 59 ,
            'movie_id' => 7 ,
            'episode' => 5 ,
            'title' => " Preferences " ,
          ],
          [
            'id' => 60 ,
            'movie_id' => 7 ,
            'episode' => 6 ,
            'title' => " Airspeeds " ,
          ],
          [
            'id' => 61 ,
            'movie_id' => 7 ,
            'episode' => 7 ,
            'title' => " Cake " ,
          ],
          [
            'id' => 62 ,
            'movie_id' => 7 ,
            'episode' => 8 ,
            'title' => " Bubbles " ,
          ],
          [
            'id' => 63 ,
            'movie_id' => 7 ,
            'episode' => 9 ,
            'title' => " Windlass " ,
          ],
          [
            'id' => 64 ,
            'movie_id' => 8 ,
            'episode' => 1 ,
            'title' => " Tubing " ,
          ],
          [
            'id' => 65 ,
            'movie_id' => 8 ,
            'episode' => 2 ,
            'title' => " Harpoon " ,
          ],
          [
            'id' => 66 ,
            'movie_id' => 8 ,
            'episode' => 3 ,
            'title' => " Riding " ,
          ],
          [
            'id' => 67 ,
            'movie_id' => 8 ,
            'episode' => 4 ,
            'title' => " Offers " ,
          ],
          [
            'id' => 68 ,
            'movie_id' => 8 ,
            'episode' => 5 ,
            'title' => " Fellow " ,
          ],
          [
            'id' => 69 ,
            'movie_id' => 8 ,
            'episode' => 6 ,
            'title' => " Habit " ,
          ],
          [
            'id' => 70 ,
            'movie_id' => 8 ,
            'episode' => 7 ,
            'title' => " Stoppering " ,
          ],
          [
            'id' => 71 ,
            'movie_id' => 8 ,
            'episode' => 8 ,
            'title' => " Adverb " ,
          ],
          [
            'id' => 72 ,
            'movie_id' => 8 ,
            'episode' => 9 ,
            'title' => " Skip " ,
          ],
          [
            'id' => 73 ,
            'movie_id' => 9 ,
            'episode' => 1 ,
            'title' => " Taxes " ,
          ],
          [
            'id' => 74 ,
            'movie_id' => 9 ,
            'episode' => 2 ,
            'title' => " Operability " ,
          ],
          [
            'id' => 75 ,
            'movie_id' => 9 ,
            'episode' => 3 ,
            'title' => " Bread " ,
          ],
          [
            'id' => 76 ,
            'movie_id' => 9 ,
            'episode' => 4 ,
            'title' => " Nameplates " ,
          ],
          [
            'id' => 77 ,
            'movie_id' => 9 ,
            'episode' => 5 ,
            'title' => " Convulsions " ,
          ],
          [
            'id' => 78 ,
            'movie_id' => 9 ,
            'episode' => 6 ,
            'title' => " Flashes " ,
          ],
          [
            'id' => 79 ,
            'movie_id' => 9 ,
            'episode' => 7 ,
            'title' => " Insignias " ,
          ],
          [
            'id' => 80 ,
            'movie_id' => 9 ,
            'episode' => 8 ,
            'title' => " Canals " ,
          ],
          [
            'id' => 81 ,
            'movie_id' => 9 ,
            'episode' => 9 ,
            'title' => " Pay " ,
          ],
          [
            'id' => 82 ,
            'movie_id' => 10 ,
            'episode' => 1 ,
            'title' => " Cheats " ,
          ],
          [
            'id' => 83 ,
            'movie_id' => 10 ,
            'episode' => 2 ,
            'title' => " Requisition " ,
          ],
          [
            'id' => 84 ,
            'movie_id' => 10 ,
            'episode' => 3 ,
            'title' => " Dopes " ,
          ],
          [
            'id' => 85 ,
            'movie_id' => 10 ,
            'episode' => 4 ,
            'title' => " Neglect " ,
          ],
          [
            'id' => 86 ,
            'movie_id' => 10 ,
            'episode' => 5 ,
            'title' => " Jellies " ,
          ],
          [
            'id' => 87 ,
            'movie_id' => 10 ,
            'episode' => 6 ,
            'title' => " Fallout " ,
          ],
          [
            'id' => 88 ,
            'movie_id' => 10 ,
            'episode' => 7 ,
            'title' => " Navigators " ,
          ],
          [
            'id' => 89 ,
            'movie_id' => 10 ,
            'episode' => 8 ,
            'title' => " Series " ,
          ],
          [
            'id' => 90 ,
            'movie_id' => 10 ,
            'episode' => 9 ,
            'title' => " Cargo " ,
          ],
          [
            'id' => 91 ,
            'movie_id' => 11 ,
            'episode' => 1 ,
            'title' => " Hunt " ,
          ],
          [
            'id' => 92 ,
            'movie_id' => 11 ,
            'episode' => 2 ,
            'title' => " Instance " ,
          ],
          [
            'id' => 93 ,
            'movie_id' => 11 ,
            'episode' => 3 ,
            'title' => " Conjecture " ,
          ],
          [
            'id' => 94 ,
            'movie_id' => 11 ,
            'episode' => 4 ,
            'title' => " Fats " ,
          ],
          [
            'id' => 95 ,
            'movie_id' => 11 ,
            'episode' => 5 ,
            'title' => " Plant " ,
          ],
          [
            'id' => 96 ,
            'movie_id' => 11 ,
            'episode' => 6 ,
            'title' => " Airport " ,
          ],
          [
            'id' => 97 ,
            'movie_id' => 11 ,
            'episode' => 7 ,
            'title' => " Dominions " ,
          ],
          [
            'id' => 98 ,
            'movie_id' => 11 ,
            'episode' => 8 ,
            'title' => " Environment " ,
          ],
          [
            'id' => 99 ,
            'movie_id' => 11 ,
            'episode' => 9 ,
            'title' => " Discard " ,
          ],
          [
            'id' => 100 ,
            'movie_id' => 12 ,
            'episode' => 1 ,
            'title' => " Guess " ,
          ],
          [
            'id' => 101 ,
            'movie_id' => 12 ,
            'episode' => 2 ,
            'title' => " Gyros " ,
          ],
          [
            'id' => 102 ,
            'movie_id' => 12 ,
            'episode' => 3 ,
            'title' => " Key " ,
          ],
          [
            'id' => 103 ,
            'movie_id' => 12 ,
            'episode' => 4 ,
            'title' => " Flower " ,
          ],
          [
            'id' => 104 ,
            'movie_id' => 12 ,
            'episode' => 5 ,
            'title' => " Crust " ,
          ],
          [
            'id' => 105 ,
            'movie_id' => 12 ,
            'episode' => 6 ,
            'title' => " Precautions " ,
          ],
          [
            'id' => 106 ,
            'movie_id' => 12 ,
            'episode' => 7 ,
            'title' => " Rumbles " ,
          ],
          [
            'id' => 107 ,
            'movie_id' => 12 ,
            'episode' => 8 ,
            'title' => " Result " ,
          ],
          [
            'id' => 108 ,
            'movie_id' => 12 ,
            'episode' => 9 ,
            'title' => " Session " ,
          ],
      ]);
    }
}
